apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "dashy.fullname" . }}
  labels:
    type: local
spec:
  capacity:
    storage: 8Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: simple
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '1'
      staleReplicaTimeout: '2880'
    volumeHandle: {{ include "dashy.fullname" . }}
  accessModes:
    - ReadWriteOnce
